scan:
  # 扫描路径
  directory: "C:\\Users\\admin\\Desktop\\掘金小册\\"
  match: 
    # 匹配Markdown文件的正则表达式
    md_regex: ".*\\.md$"
    # 匹配图片链接的正则表达式
    # pic_regex = re.compile(r"!\[.*\]\((.*?)\)")
    pic_regex: "(!\\[.*?\\]\\((.*?)\\)|<img\\s+src\\s*=\\s*['\"](.*?)['\"].*?>)"
    # 扫描结果文件
    result_filepath: "output.json"
migrate:
  # picgo相关配置
  picgo:
    # 上传地址
    server_url: "http://127.0.0.1:36677/upload"
log:
   filepath: ./app.log